/* ========================================
   DAIRAS PAR WILAYA
   Clé = code de la wilaya (2 chiffres)
   Tu peux ajouter / corriger / supprimer des dairas librement.
   ======================================== */
const DAIRAS = {
    "01": ["Adrar", "Aoulef", "Bouda", "Fenoughil", "Reggane", "Sali", "Tsabit", "Zaouiet Kounta"],
    "02": ["Chlef", "Abou El Hassan", "Aïn Merane", "Béni Haoua", "Boukadir", "El Karimia", "Oued Fodda", "Oued Sly", "Ouled Ben Abdelkader", "Sendjas", "Sobha", "Tadjena", "Ténès", "Zeboudja"],
    "03": ["Laghouat", "Aflou", "Aïn Madhi", "Brida", "El Ghicha", "Gueltat Sidi Saâd", "Hassi Delaa", "Hassi R'Mel", "Ksar El Hirane", "Sidi Makhlouf"],
    "04": ["Oum El Bouaghi", "Aïn Babouche", "Aïn Beïda", "Aïn Fakroun", "Aïn M'Lila", "Dhalaa", "Fkirina", "Ksar Sbahi", "Meskiana", "Sigus", "Souk Naamane"],
    "05": ["Batna", "Aïn Djasser", "Aïn Touta", "Arris", "Barika", "Bouzina", "Chemora", "Djezzar", "Ichmoul", "Menaa", "Merouana", "N'Gaous", "Ouled Si Slimane", "Ras El Aïoun", "Seggana", "Seriana", "T'Kout", "Tazoult", "Timgad"],
    "06": ["Béjaïa", "Adekar", "Akbou", "Amizour", "Aokas", "Barbacha", "Béni Maouche", "Chemini", "Darguina", "El Kseur", "Ighil Ali", "Kherrata", "Ouzellaguen", "Seddouk", "Sidi Aïch", "Souk El Tenine", "Tazmalt", "Tichy", "Timezrit"],
    "07": ["Biskra", "Djemorah", "El Kantara", "El Outaya", "Foughala", "M'Chouneche", "Ourlal", "Sidi Okba", "Tolga", "Zeribet El Oued"],
    "08": ["Béchar", "Abadla", "Béni Ounif", "Kenadsa", "Lahmar", "Mechraa Houari Boumédiène", "Taghit"],
    "09": ["Blida", "Boufarik", "Bougara", "Bouinan", "Larbaâ", "Meftah", "Mouzaïa", "Oued El Alleug", "Ouled Yaïch"],
    "10": ["Bouira", "Aïn Bessem", "Bechloul", "Bir Ghbalou", "Bordj Okhriss", "El Hachimia", "Haizer", "Kadiria", "Lakhdaria", "M'Chedallah", "Sour El Ghozlane", "Souk El Khemis"],
    "11": ["Tamanrasset", "Abalessa", "Idlès", "In Amguel", "Tazrouk"],
    "12": ["Tébessa", "Bekkaria", "Bir El Ater", "Bir Mokkadem", "Cheria", "El Aouinet", "El Kouif", "El Ma El Abiod", "Hammamet", "Morsott", "Negrine", "Ouenza"],
    "13": ["Tlemcen", "Aïn Tallout", "Bab El Assa", "Beni Snous", "Chetouane", "Fellaoucene", "Ghazaouet", "Hennaya", "Honaïne", "Maghnia", "Mansourah", "Marsa Ben M'Hidi", "Nedroma", "Ouled Mimoun", "Remchi", "Sabra", "Sebdou", "Sidi Djillali"],
    "14": ["Tiaret", "Aïn Deheb", "Aïn Kermes", "Dahmouni", "Frenda", "Hamadia", "Ksar Chellala", "Mahdia", "Mechraa Sfa", "Medroussa", "Mellakou", "Oued Lili", "Rahouia", "Sidi Ali Mellal", "Sougueur"],
    "15": ["Tizi Ouzou", "Aïn El Hammam", "Aïn Zaouia", "Azazga", "Azeffoun", "Beni Douala", "Beni Yenni", "Boghni", "Bouzeguène", "Draâ Ben Khedda", "Draâ El Mizan", "Iferhounène", "Larbaâ Nath Irathen", "Maâtkas", "Makouda", "Mekla", "Ouacifs", "Ouadhia", "Ouaguenoun", "Tigzirt", "Tizi Ghenif", "Tizi Rached", "Yakouren"],
    "16": ["Sidi M'Hamed", "Bab El Oued", "Bologhine", "Hussein Dey", "El Harrach", "Dar El Beïda", "Rouiba", "Baraki", "Birtouta", "Bir Mourad Raïs", "Bouzaréah", "Chéraga", "Draria", "Zéralda"],
    "17": ["Djelfa", "Aïn El Ibel", "Aïn Oussara", "Birine", "Charef", "Dar Chioukh", "El Idrissia", "Faïd El Botma", "Hassi Bahbah", "Messaad", "Moudjebara", "Sidi Laadjel"],
    "18": ["Jijel", "Chekfa", "Djimla", "El Ancer", "El Aouana", "El Milia", "Settara", "Sidi Maarouf", "Taher", "Texenna", "Ziama Mansouriah"],
    "19": ["Sétif", "Aïn Arnat", "Aïn Azel", "Aïn El Kebira", "Aïn Oulmène", "Amoucha", "Babor", "Beidha Bordj", "Béni Aziz", "Bir El Arch", "Bouandas", "Bougaâ", "Djemila", "El Eulma", "Guenzet", "Hammam Guergour", "Hammam Sokhna", "Maoklane", "Salah Bey"],
    "20": ["Saïda", "Aïn El Hadjar", "Doui Thabet", "El Hassasna", "Ouled Brahim", "Sidi Boubekeur", "Youb"],
    "21": ["Skikda", "Aïn Charchar", "Aïn Kechra", "Azzaba", "Collo", "El Hadaïek", "El Harrouch", "Ouled Attia", "Ramdane Djamel", "Sidi Mezghiche", "Tamalous", "Zitouna"],
    "22": ["Sidi Bel Abbès", "Aïn El Berd", "Ben Badis", "Marhoum", "Merine", "Mostefa Ben Brahim", "Moulay Slissen", "Ras El Ma", "Sfisef", "Sidi Ali Boussidi", "Sidi Lahcène", "Tenira", "Tessala", "Télagh"],
    "23": ["Annaba", "Aïn Berda", "Berrahal", "Chetaïbi", "El Bouni", "El Hadjar", "Seraïdi"],
    "24": ["Guelma", "Aïn Makhlouf", "Bouati Mahmoud", "Bouchegouf", "Hammam Debagh", "Héliopolis", "Khezaras", "Oued Zenati", "Tamlouka"],
    "25": ["Constantine", "Aïn Smara", "Béni Hamidene", "Didouche Mourad", "El Khroub", "Hamma Bouziane", "Ibn Ziad", "Zighoud Youcef"],
    "26": ["Médéa", "Aïn Boucif", "Baata", "Beni Slimane", "Berrouaghia", "Chellalet El Adhaoura", "El Omaria", "Ksar El Boukhari", "Ouamri", "Ouzera", "Seghouane", "Si Mahdjoub", "Souagui", "Tablat"],
    "27": ["Mostaganem", "Achaacha", "Aïn Nouissy", "Aïn Tedeles", "Bouguirat", "Hassi Mameche", "Khayr Eddine", "Mesra", "Sidi Ali", "Sidi Lakhdar", "Stidia"],
    "28": ["M'Sila", "Aïn El Hadjel", "Aïn El Melh", "Belaïba", "Ben Srour", "Bou Saâda", "Chellal", "Djebel Messaâd", "Hammam Dalaâ", "Magra", "Maâdid", "Ouled Derradj", "Sidi Aïssa", "Sidi Ameur"],
    "29": ["Mascara", "Aïn Fares", "Aïn Fekan", "Bou Hanifia", "Ghriss", "Hacine", "Mamounia", "Mohammadia", "Oued El Abtal", "Sig", "Tighennif", "Tizi", "Zahana"],
    "30": ["Ouargla", "El Borma", "Hassi Messaoud", "N'Goussa", "Rouissat", "Sidi Khouiled"],
    "31": ["Oran", "Aïn El Turck", "Arzew", "Bethioua", "Bir El Djir", "Boutlélis", "Es Sénia", "Gdyel", "Oued Tlélat", "Sidi Chami"],
    "32": ["El Bayadh", "Boualem", "Bougtoub", "Brézina", "Chellala", "El Abiodh Sidi Cheikh", "Rogassa", "Stitten"],
    "33": ["Illizi", "Bordj Omar Driss", "Debdeb", "In Amenas"],
    "34": ["Bordj Bou Arreridj", "Aïn Taghrout", "Bir Kasdali", "Bordj Ghdir", "Bordj Zemoura", "Djaâfra", "El Hamadia", "El Mansoura", "Medjana", "Ras El Oued"],
    "35": ["Boumerdès", "Baghlia", "Bordj Menaïel", "Boudouaou", "Dellys", "Isser", "Khemis El Khechna", "Naciria", "Ouled Moussa", "Thénia"],
    "36": ["El Tarf", "Aïn El Assel", "Ben M'Hidi", "Besbes", "Bouhadjar", "Bouteldja", "Dréan", "El Kala"],
    "37": ["Tindouf", "Oum El Assel"],
    "38": ["Tissemsilt", "Bordj Bounaama", "Bordj El Emir Abdelkader", "Khemisti", "Lardjem", "Layoune", "Théniet El Had"],
    "39": ["El Oued", "Bayadha", "Debila", "Guemar", "Hassani Abdelkrim", "Hassi Khalifa", "Magrane", "Mih Ouensa", "Nakhla", "Reguiba", "Robbah", "Taleb Larbi"],
    "40": ["Khenchela", "Aïn Touila", "Babar", "Bouhmama", "Chechar", "El Hamma", "Kaïs", "Ouled Rechache", "Tamza"],
    "41": ["Souk Ahras", "Aïn Zana", "Bir Bouhouche", "Haddada", "M'Daourouch", "Mechroha", "Merahna", "Ouled Driss", "Sedrata", "Taoura"],
    "42": ["Tipaza", "Aïn Tagourait", "Bou Ismaïl", "Cherchell", "Damous", "Fouka", "Gouraya", "Hadjout", "Koléa", "Menaceur", "Sidi Amar", "Sidi Ghiles"],
    "43": ["Mila", "Aïn Beïda", "Aïn Mellouk", "Chelghoum Laïd", "Ferdjioua", "Grarem Gouga", "Oued Athmania", "Rouached", "Sidi Merouane", "Tadjenanet", "Tassadane Haddada", "Teleghma"],
    "44": ["Aïn Defla", "Aïn Bouyahia", "Aïn Lechiakh", "Bathia", "Bordj Emir Khaled", "Boumedfaa", "Djelida", "Djendel", "El Abadia", "El Attaf", "Hammam Righa", "Khemis Miliana", "Miliana", "Rouina"],
    "45": ["Naâma", "Aïn Sefra", "Asla", "Mécheria", "Mekmen Ben Amar", "Moghrar", "Tiout"],
    "46": ["Aïn Témouchent", "Aïn El Arbaa", "Béni Saf", "El Amria", "El Malah", "Hammam Bou Hadjar", "Oulhaça El Gheraba"],
    "47": ["Ghardaïa", "Berriane", "Bounoura", "Dhayet Bendhahoua", "El Atteuf", "Guerrara", "Metlili", "Zelfana"],
    "48": ["Relizane", "Aïn Tarek", "Ammi Moussa", "Djidiouia", "El Matmar", "Mazouna", "Mendes", "Oued Rhiou", "Sidi M'Hamed Ben Ali", "Yellel", "Zemmora"],
    "49": ["Timimoun", "Aougrout", "Charouine", "Tinerkouk"],
    "50": ["Bordj Badji Mokhtar", "Timiaouine"],
    "51": ["Ouled Djellal", "Doucen", "Ras El Miaad", "Sidi Khaled"],
    "52": ["Béni Abbès", "El Ouata", "Igli", "Kerzaz", "Ouled Khoudir", "Tabelbala", "Timoudi"],
    "53": ["In Salah", "Foggaret Ezzaouia", "In Ghar"],
    "54": ["In Guezzam", "Tin Zaouatine"],
    "55": ["Touggourt", "Blidet", "Megarine", "Taïbet", "Témacine"],
    "56": ["Djanet", "Bordj El Haouas"],
    "57": ["El M'Ghair", "Djamaa", "Sidi Amrane", "Still"],
    "58": ["El Meniaa", "Hassi Gara"]
};
